### PR TITLE
prevent a default Hash::Merge instance from creating memory leaks

### PR DESCRIPTION
**Pull request by wchristian**
Fix for https://rt.cpan.org/Ticket/Display.html?id=132627

### CODE REVIEW

**Review by rehsack — APPROVED** [review]

**Comment by wchristian** [comment]
Any chance of seeing this merged and released, given it affects all downstream dependencies? :)

**Comment by rehsack** [comment]
> Any chance of seeing this merged and released, given it affects all downstream dependencies? :)

I cannot speak for @sh85 - whether he takes the opportunity or not - I will pick it up when updating [meta-cpan](https://github.com/meta-cpan/meta-cpan) next time - which is planned in July/August.

**Comment by wchristian** [comment]
Can i get comaint?

**Comment by rehsack** [comment]
Short: no'ish.
@sh85 tries to find a tuit next week.

**Comment by rehsack** [comment]
Understood. When we meet next TPC or GPW, we can talk about that.

**Comment by wchristian** [comment]
Unlikely to happen at this point for a long time. My email/irc/telegram/etc's always open. :)

**Comment by rehsack** [comment]
For co-maint this is mandatory until I'm giving up p5.

**Pull request merged**
